# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_auto_20170917_2217'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medications.MedicationTime'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('L', 'Liked'), ('C', 'Commented'), ('F', 'Favorited'), ('A', 'Answered'), ('W', 'Accepted Answer'), ('E', 'Edited Article'), ('S', 'Also Commented'), ('OD', 'Overdue Medication')], max_length=1),
        ),
    ]
