# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-26 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20170826_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualuser',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[(0, 'Administrator'), (1, 'Patient')], default=1, max_length=20),
        ),
        migrations.DeleteModel(
            name='IndividualUser',
        ),
    ]
