# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pinnumber',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
    ]
