# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_profile_pinnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emailnotify',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='smsnotify',
            field=models.NullBooleanField(default=True),
        ),
    ]
