# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20170904_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pharmacy',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
