# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20170911_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobilenumber',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
