# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-03 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20170926_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration_complete',
            field=models.BooleanField(default=False, verbose_name='Registration Complete'),
        ),
    ]
