# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-25 22:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicationName', models.CharField(blank=True, default='Medication', max_length=50, null=True, verbose_name='Medication Name')),
                ('medicationSlug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('medicationDosage', models.CharField(blank=True, default='e.g. 120 mg', max_length=50, null=True, verbose_name='Dosage')),
                ('medicationFrequency', models.CharField(blank=True, choices=[('0', 'PRN - As Needed'), ('1', 'QD - 1 Times A Day'), ('2', 'BID - 2 Times A Day'), ('3', 'TID - 3 Timse A Day'), ('4', 'QID - 4 times a day'), ('5', 'SID - 5 times a day'), ('6', '6 times a day')], max_length=50, null=True, verbose_name='Frequency')),
                ('medicationQuantity', models.IntegerField(blank=True, default='30', null=True, verbose_name='Quantity')),
                ('medicationType', models.CharField(blank=True, default='Need Options', max_length=20, null=True, verbose_name='Drug Type')),
                ('medicationComment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Physician Orders')),
                ('medicationStartDate', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Medication Start Date')),
                ('medicationTimeSchedule', models.TimeField(blank=True, null=True, verbose_name='Time 1')),
                ('medicationTimeSchedule2', models.TimeField(blank=True, null=True, verbose_name='Time 2')),
                ('medicationTimeSchedule3', models.TimeField(blank=True, null=True, verbose_name='Time 3')),
                ('medicationTimeSchedule4', models.TimeField(blank=True, null=True, verbose_name='Time 4')),
                ('medicationTimeSchedule5', models.TimeField(blank=True, null=True, verbose_name='Time 5')),
                ('medicationTimeSchedule6', models.TimeField(blank=True, null=True, verbose_name='Time 6')),
                ('medicationDiscontinuedStatus', models.CharField(blank=True, choices=[('Active', 'Active'), ('Discontinued', 'Discontinued')], default='Active', max_length=15, null=True, verbose_name='DC Status')),
                ('medicationDateTimeAdded', models.DateTimeField(auto_now_add=True)),
                ('medicationMissed', models.CharField(blank=True, choices=[('False', 'False'), ('True', 'True')], default='False', max_length=12, null=True, verbose_name='Medication Missed')),
                ('medicationRecordReset', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('medicationPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-medicationName',),
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
            },
        ),
        migrations.CreateModel(
            name='MedicationCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completionStatus', models.NullBooleanField(choices=[(True, 'Accepted'), (False, 'Refused')], default=None, verbose_name='Current Status')),
                ('completionStatus2', models.CharField(blank=True, choices=[('Null', 'Null'), ('False', 'False'), ('True', 'True')], max_length=12, null=True, verbose_name='Current Status 2')),
                ('completionMissed', models.CharField(blank=True, choices=[('False', 'False'), ('True', 'True')], default='False', max_length=12, null=True, verbose_name='Medicaton Missed')),
                ('completionTime', models.TimeField(auto_now_add=True, verbose_name='Time Given')),
                ('completionDue', models.TimeField(blank=True, null=True, verbose_name='Time Due')),
                ('completionDate', models.DateField(verbose_name='Date Given')),
                ('completionNote', models.CharField(blank=True, max_length=500, null=True, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeDue', models.TimeField(blank=True, null=True, verbose_name='Time Due')),
                ('timeDelivered', models.TimeField(blank=True, null=True, verbose_name='Time Delivered')),
                ('timeStatus', models.NullBooleanField(choices=[(True, 'Accepted'), (False, 'Refused')], default=None, verbose_name='Medication')),
                ('timeGivenStatus', models.CharField(blank=True, choices=[('Null', 'Null'), ('False', 'False'), ('True', 'True')], default=None, max_length=12, null=True, verbose_name='Given')),
                ('timeGivenDate', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('timeGivenNote', models.CharField(blank=True, max_length=500, null=True, verbose_name='Notes')),
                ('timePRN', models.NullBooleanField(default=None, verbose_name='PRN?')),
                ('timeCreated', models.DateTimeField(verbose_name='Created')),
                ('timeMedication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.Medication')),
            ],
        ),
        migrations.AddField(
            model_name='medicationcompletion',
            name='completionMedication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='medications.MedicationTime'),
        ),
        migrations.AddField(
            model_name='medicationcompletion',
            name='completionRx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.Medication'),
        ),
    ]
