# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_auto_20170826_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Patient'),
        ),
    ]
