# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_sendsms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationcompletion',
            name='completionRx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mymedication', to='medications.Medication'),
        ),
    ]
