# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_auto_20170917_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationtime',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
