# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-02 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0007_medicationtime_is_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationcompletion',
            name='completionEdited',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Medicaton Edited'),
        ),
        migrations.AddField(
            model_name='medicationcompletion',
            name='completionEditedDate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Date Edited:'),
        ),
        migrations.AddField(
            model_name='medicationcompletion',
            name='completionEditedUser',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Edited by:'),
        ),
    ]
