# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-02 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0010_auto_20171002_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationcompletion',
            name='completionEdited',
        ),
    ]
