# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-02 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medications', '0012_auto_20171002_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationCompletionChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEdited', models.DateTimeField(auto_now_add=True)),
                ('medicationRx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.Medication')),
                ('medicationTime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.MedicationTime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
